#' Generate Icon CSS from Images
#'
#' Development helper that takes a folder of images and generates CSS file
#' with icon classes. Images are copied to output folder and CSS references them.
#'
#' @param images_dir Path to folder containing source images (PNG, JPG, SVG)
#' @param output_dir Path where CSS and images will be saved (e.g., "www/my_icons")
#' @param prefix CSS class prefix (e.g., "my-icon-" creates classes like .my-icon-cat)
#' @param css_filename Name of generated CSS file (default: "icons.css")
#' @param width Icon width in pixels (default: 24)
#' @param height Icon height in pixels (default: 18)
#' @param mapping Optional named list mapping filenames to class codes
#'   (e.g., list("kenya.png" = "ken")). If NULL, uses filename as code.
#' @param overwrite Overwrite existing files (default: FALSE)
#'
#' @return Invisibly returns list with generated CSS path and icon names
#'
#' @examples
#' \dontrun{
#' # Simple usage - class names from filenames
#' generate_icon_css(
#'   images_dir = "raw_images/species",
#'   output_dir = "www/species_icons",
#'   prefix = "species-"
#' )
#'
#' # With custom mapping - filename to code
#' generate_icon_css(
#'   images_dir = "raw_images/flags",
#'   output_dir = "www/flags",
#'   prefix = "flag-",
#'   mapping = list(
#'     "kenya.png" = "ken",
#'     "indonesia.png" = "idn"
#'   )
#' )
#'
#' # Then in your app:
#' # tags$link(rel = "stylesheet", href = "species_icons/icons.css")
#' # select_input(..., iconClass = "species-")
#' }
#'
#' @export
generate_icon_css <- function(
    images_dir,
    output_dir,
    prefix = "icon-",
    css_filename = "icons.css",
    width = 24,
    height = 18,
    mapping = NULL,
    overwrite = FALSE
) {
  # Validate input

if (!dir.exists(images_dir)) {
    stop("images_dir does not exist: ", images_dir)
  }

  # Create output directory
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
    message("Created output directory: ", output_dir)
  }

  # Find image files
  image_extensions <- c("png", "jpg", "jpeg", "svg", "gif", "webp")
  pattern <- paste0("\\.(",
    paste(image_extensions, collapse = "|"), ")$")
  image_files <- list.files(images_dir, pattern = pattern, ignore.case = TRUE)

  if (length(image_files) == 0) {
    stop("No image files found in: ", images_dir)
  }

  message("Found ", length(image_files), " images")

  # Generate CSS
  css_lines <- c(
    paste0("/* Generated by primereact::generate_icon_css() */"),
    paste0("/* Source: ", images_dir, " */"),
    paste0("/* Date: ", Sys.time(), " */"),
    ""
  )

  icon_names <- c()

  for (img_file in image_files) {
    # Get icon name: use mapping if provided, otherwise use filename
    if (!is.null(mapping) && img_file %in% names(mapping)) {
      icon_name <- tolower(mapping[[img_file]])
    } else {
      icon_name <- tolower(tools::file_path_sans_ext(img_file))
    }
    icon_name <- gsub("[^a-z0-9]", "-", icon_name)  # sanitize
    icon_names <- c(icon_names, icon_name)

    # Copy image to output
    src_path <- file.path(images_dir, img_file)
    dest_path <- file.path(output_dir, img_file)

    if (file.exists(dest_path) && !overwrite) {
      message("  Skipping (exists): ", img_file)
    } else {
      file.copy(src_path, dest_path, overwrite = overwrite)
      message("  Copied: ", img_file)
    }

    # Add CSS rule
    css_lines <- c(css_lines, paste0(
      ".", prefix, icon_name, " {",
      " background: url(\"", img_file, "\") no-repeat center;",
      " background-size: contain;",
      " width: ", width, "px;",
      " height: ", height, "px;",
      " display: inline-block;",
      " }"
    ))
  }

  # Write CSS file
  css_path <- file.path(output_dir, css_filename)
  writeLines(css_lines, css_path)
  message("\nGenerated CSS: ", css_path)
  message("Icon classes: .", prefix, "<name>")
  message("\nUsage in Shiny:")
  message('  tags$link(rel = "stylesheet", href = "',
    basename(output_dir), "/", css_filename, '")')
  message('  select_input(..., iconClass = "', prefix, '")')

  invisible(list(
    css_path = css_path,
    icons = icon_names,
    prefix = prefix
  ))
}
